name: Bugfix Branch Workflow

on:
  push:
    branches:
      - 'bugfix-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Add your bugfix branch workflow steps here
