name: Hotfix Branch Workflow

on:
  push:
    branches:
      - 'hotfix-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Add your hotfix branch workflow steps here
