name: Feature Branch Workflow

on:
  push:
    branches:
      - 'feature-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Add your feature branch workflow steps here
