name: PRD Main Workflow




on:
  push:
    branches:
      - 'prd-main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Add your release branch workflow steps here
