name: Sync Branches Workflow

on:
  push:
    branches:
      - prd-main
  pull_request:
    types:
      - closed

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sync branches
        run: |
          git fetch --prune
          for branch in $(git branch -r | grep -v prd-main); do
            local_branch=$(basename $branch)
            git show-ref --verify --quiet "refs/heads/$local_branch" || git checkout --track $branch -B $local_branch
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
